### ISSUE TITLE
bud build "succeeds" but the binary is not valid

### ISSUE THREAD

**Issue by phillipp** [indutny/bud#90]
I wanted to upgrade to a current bud version but failed to do so.

I tried with npm version 2.15.0 which gives me the following:

```
make: gypkg: Command not found
make: *** [build] Error 127
npm ERR! Linux 4.3.3-040303-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "bud@4.0.6"
npm ERR! node v0.12.12
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! bud@4.0.6 preinstall: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bud@4.0.6 preinstall script 'make build'.
npm ERR! This is most likely a problem with the bud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls bud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

I tried upgrading NPM to a current version but the file that is built is not even an executable, I get the following when executing it:

```
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
/usr/bin/bud: 2: /usr/bin/bud: Syntax error: ")" unexpected
/usr/bin/bud: 1: /usr/bin/bud: ^U: not found
/usr/bin/bud: 1: /usr/bin/bud: <CF><FA><ED><FE>^G^A^C<80>^B^O<80>^G<85>: not found
```

I suppose this is not expected. Is there a stable upgrade path from 4.0.2 to 4.0.6?

**Comment by indutny** [comment]
@phillipp The build process has been changed, please either run it as a non-root user or with `npm --unsafe-perm install -g bud`.

NOTE: It will also confirm GPG keys on install.

**Comment by indutny** [comment]
@phillipp nah, it won't help. Sorry!

Looking into it.

To work it around, you may want to install v6 node.js (sorry, this is a requirement right now, please let me know if this is unacceptable for you):

```console
git clone --recursive git://github.com/indutny/bud
cd bud
npm install
npm run preinstall
npm install -g
```

**Comment by indutny** [comment]
`npm install -g` should also work if you will install node using `nvm`. It seems that the build script fails when node is installed in `/usr/local/...`, and `nvm` installs it locally.

**Comment by databeille** [comment]
Similar problem here.
Fixed it by updating node to v6.4 + npm install -g gypkg + updating git from git-1.7.1-4.el6_7.1.x86_64.rpm to git-1.7.12.4-1.el6.rfx.rpm ("branch --list" option was not recognized and made gypkg hang).

**Comment by indutny** [comment]
@databeille yikes, sorry to make you go through all of this. I'll see if I can improve this experience!

**Comment by databeille** [comment]
@indutny no worries, it is my coin to this beautiful software.

Also, I had to use "--unsafe-perm" to make the compilation successful.

**Comment by indutny** [comment]
@databeille I'm no longer using `git tag --list` in the latest gypkg, so it should be working with older git versions too now.

**Comment by phillipp** [comment]
I tried to update again to 4.0.6 and still can't compile out of the box. The build is failing with a problem with gypkg:

```
make: gypkg: Command not found
make: *** [build] Error 127
npm ERR! Linux 4.1.8-040108-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bud@4.0.6"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! bud@4.0.6 preinstall: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the bud@4.0.6 preinstall script 'make build'.
npm ERR! This is most likely a problem with the bud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

Wouldn't it make sense to include it as a dependency so the package is more self-contained? Otherwise it would be good to add gypkg to the installation instructions - I certanily had it not installed on the prod machine, I don't even know what it is...

**Comment by indutny** [comment]
@phillipp I'm terribly sorry for this, will try to figure it out ASAP!

**Comment by indutny** [comment]
@phillipp it should work on v4 node.js now, will figure out the rest very soon.

**Comment by indutny** [comment]
@phillipp should be fixed in bud@4.0.8, please let me know if it doesn't work. Closing this issue for now.

_(NOTE: bud now requires some minor user input when installed, this is to due to the verification of GPG signatures of the dependencies)_

**Comment by indutny** [comment]
Alright, it doesn't require a user input as of bud@4.0.9 .

**Comment by phillipp** [comment]
Wow, that worked! Thank you very much!

**Comment by indutny** [comment]
@phillipp you're more than welcome

**Comment by phillipp** [comment]
When I just started deployment of this version into production (these machines have no develoment packages on them) I noticed that it's now working on Ubuntu 12.04 LTS but not on 14.04 LTS (running node v0.12.15):

```
/usr/bin/bud -> /usr/lib/node_modules/bud/bin/bud

> bud@4.0.9 install /usr/lib/node_modules/bud
> gypkg build bud.gyp.json --insecure

/usr/lib/node_modules/bud/node_modules/gypkg/bin/gypkg:6
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 4.3.3-040303-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bud@4.0.9"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! bud@4.0.9 install: `gypkg build bud.gyp.json --insecure`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bud@4.0.9 install script 'gypkg build bud.gyp.json --insecure'.
npm ERR! This is most likely a problem with the bud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gypkg build bud.gyp.json --insecure
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bud
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls bud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

Additionally, it still is a requirement to first install gypkg (via npm).

I think gypkg might be possible to install via npm as a requirement, but I am not sure. Maybe that is one step less to install bud (or at least installation of gypkg before must be documented).

**Comment by indutny** [comment]
@phillipp I'm afraid `gypkg` works only on v4 node.js :( Separate installation of `gypkg` is not required, though!

**Comment by phillipp** [comment]
Hm, so on 14.04 LTS we'll have to stay with 4.0.2 unless we install another node version?

**Comment by indutny** [comment]
Any node version >= v4 will work too, it is just that v0.12 and before won't.
